/** 임시 노트에서 실제 키보드·클립보드·소켓·재접속을 검증한다. */
import "./load-env.mjs";
import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { randomUUID, randomBytes } from "node:crypto";
import { eq } from "drizzle-orm";
import { db, sql } from "../src/lib/db/index.ts";
import { users, spaces, spaceMembers, sessions, notes, noteDocs, tasks } from "../src/lib/db/schema.ts";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE ?? "playwright");
const base = process.env.EDITOR_TEST_URL ?? "http://localhost:3001";
const secure = base.startsWith("https:");
const userId = randomUUID(), spaceId = randomUUID(), noteId = randomUUID();
const token = randomBytes(32).toString("hex");
const cookie = { name: secure ? "__Secure-authjs.session-token" : "authjs.session-token", value: token, url: base, secure, httpOnly: true, sameSite: "Lax" };
let browser;
async function paste(page, editor, text, html = "") {
  await editor.click();
  await page.keyboard.press("Control+a");
  await editor.evaluate((element, data) => {
    const clipboardData = new DataTransfer();
    clipboardData.setData("text/plain", data.text);
    if (data.html) clipboardData.setData("text/html", data.html);
    element.dispatchEvent(new ClipboardEvent("paste", { clipboardData, bubbles: true, cancelable: true }));
  }, { text, html });
}
try {
  await db.insert(users).values({ id: userId, name: "편집 검증", email: `editor-${userId}@example.invalid` });
  await db.insert(spaces).values({ id: spaceId, name: "편집 검증", ownerId: userId });
  await db.insert(spaceMembers).values({ spaceId, userId, role: "owner" });
  await db.insert(sessions).values({ sessionToken: token, userId, expires: new Date(Date.now() + 900000) });
  await db.insert(notes).values({ id: noteId, spaceId, title: "편집 검증", createdBy: userId, template: "blank", content: { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: "처음 문단" }] }] } });
  await db.insert(noteDocs).values({ noteId });
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();
  await context.addCookies([cookie]);
  const page = await context.newPage();
  const start = Date.now();
  let sockets = 0;
  const errors = [];
  page.on("websocket", (ws) => {
    if (!ws.url().includes(noteId)) return;
    sockets++;
    console.log(`WS opened at ${Date.now() - start}ms`);
    ws.on("close", () => console.log(`WS closed at ${Date.now() - start}ms`));
  });
  page.on("pageerror", (error) => errors.push(error.message.slice(0, 200)));
  const path = `${base}/s/${spaceId}/n/${noteId}`;
  const response = await page.goto(path, { waitUntil: "domcontentloaded", timeout: 60000 });
  console.log(`DOM ready ${Date.now() - start}ms, region ${response.headers()["x-vercel-id"] ?? "local"}`);
  const editor = page.locator('.tiptap[contenteditable="true"]');
  await editor.waitFor({ timeout: 60000 });
  await editor.getByText("처음 문단", { exact: true }).waitFor({ timeout: 45000 });
  console.log(`Editable content ${Date.now() - start}ms`);
  await editor.click();
  await page.keyboard.press("Control+End");
  await page.keyboard.press("Tab");
  assert.equal(await editor.locator('p[data-indent="1"]').count(), 1);
  await page.keyboard.press("Shift+Tab");
  assert.equal(await editor.locator('p[data-indent]').count(), 0);
  console.log("PASS 일반 문단 Tab / Shift+Tab");
  await page.keyboard.press("Enter");
  await page.keyboard.type("- ");
  await page.keyboard.insertText("목록 첫 항목");
  await page.keyboard.press("Enter");
  await page.keyboard.insertText("목록 하위 항목");
  await page.keyboard.press("Tab");
  assert.equal(await editor.locator("ul ul").count(), 1);
  assert.equal(await editor.locator("ul").first().evaluate((el) => getComputedStyle(el).listStyleType), "disc");
  await page.keyboard.press("Shift+Tab");
  assert.equal(await editor.locator("ul ul").count(), 0);
  console.log("PASS 목록 문법·글머리표·들여쓰기");
  await paste(page, editor, "붙여넣은 제목\n첫 번째 문단\n두 번째 문단\n항목 A\n항목 B", '<h1>붙여넣은 제목</h1><p>첫 번째 <strong>문단</strong></p><p>두 번째 문단</p><ul><li>항목 A</li><li>항목 B</li></ul>');
  assert.equal(await editor.locator("h1").textContent(), "붙여넣은 제목");
  assert.equal(await editor.locator("strong").textContent(), "문단");
  assert.equal(await editor.locator("ul > li").count(), 2);
  assert.ok(parseFloat(await editor.locator("h1").evaluate((el) => getComputedStyle(el).fontSize)) > 20);
  console.log("PASS HTML 제목·문단·굵은 글씨·목록 붙여넣기");
  await paste(page, editor, "# 마크다운 제목\n\n첫 문단\n다음 줄\n\n- 첫 항목\n  - 하위 항목\n\n1. 번호 항목\n\n- [ ] 할 일 A\n- [x] 할 일 B");
  assert.equal(await editor.locator("h1").textContent(), "마크다운 제목");
  assert.equal(await editor.locator("ul ul").count(), 1);
  assert.equal(await editor.locator("ol").count(), 1);
  assert.equal(await editor.locator('ul[data-type="taskList"] > li').count(), 2);
  assert.equal(await editor.locator('li[data-checked="true"]').count(), 1);
  console.log("PASS 텍스트 마크다운 붙여넣기");
  await paste(page, editor, "첫 문단\n둘째 문단\n셋째 문단");
  assert.deepEqual(await editor.locator("p").allTextContents(), ["첫 문단", "둘째 문단", "셋째 문단"]);
  console.log("PASS 일반 텍스트 문단 보존");
  await paste(page, editor, "", '<p data-indent="2">들여쓴 문단</p><ul data-type="taskList"><li data-type="taskItem" data-checked="false"><p>부모 할 일</p></li><li data-type="taskItem" data-checked="false"><p>하위 할 일</p></li></ul><p>두 창 동기화</p>');
  await editor.getByText("하위 할 일", { exact: true }).click({ position: { x: 12, y: 12 } });
  await page.waitForFunction(() => window.getSelection()?.anchorNode?.parentElement?.closest("p")?.textContent === "하위 할 일");
  await page.keyboard.press("Tab");
  assert.equal(await editor.locator('ul[data-type="taskList"] ul[data-type="taskList"]').count(), 1);
  await page.keyboard.press("Shift+Tab");
  assert.equal(await editor.locator('ul[data-type="taskList"] ul[data-type="taskList"]').count(), 0);
  await page.keyboard.press("Tab");
  console.log("PASS 체크박스 Tab / Shift+Tab");
  await page.waitForTimeout(65000);
  assert.equal(sockets, 1, "혼자 편집 중 무응답 재연결이 없어야 한다");
  const storedTasks = await db.select().from(tasks).where(eq(tasks.noteId, noteId));
  assert.deepEqual(storedTasks.map((t) => t.body).sort(), ["부모 할 일", "하위 할 일"].sort());
  console.log("PASS 65초 단일 연결 유지·중첩 할 일 본문 분리");
  const peerContext = await browser.newContext();
  await peerContext.addCookies([cookie]);
  const peer = await peerContext.newPage();
  const peerStart = Date.now();
  await peer.goto(path, { waitUntil: "domcontentloaded", timeout: 60000 });
  const peerEditor = peer.locator('.tiptap[contenteditable="true"]');
  await peerEditor.waitFor({ timeout: 45000 });
  console.log(`Warm editable content ${Date.now() - peerStart}ms`);
  await editor.getByText("두 창 동기화", { exact: true }).click({ position: { x: 12, y: 12 } });
  await page.waitForFunction(() => window.getSelection()?.anchorNode?.parentElement?.closest("p")?.textContent === "두 창 동기화");
  await page.keyboard.press("Control+End");
  await page.keyboard.insertText(" 완료");
  await peerEditor.locator("p").filter({ hasText: "두 창 동기화 완료" }).first().waitFor({ timeout: 15000 });
  console.log("PASS 독립 브라우저 창 실시간 동기화");
  await page.waitForTimeout(4000);
  await peer.reload({ waitUntil: "domcontentloaded" });
  await peerEditor.locator("p").filter({ hasText: "두 창 동기화 완료" }).first().waitFor({ timeout: 45000 });
  assert.equal(await peerEditor.locator('p[data-indent="2"]').textContent(), "들여쓴 문단");
  assert.equal(await peerEditor.locator('ul[data-type="taskList"] ul[data-type="taskList"]').count(), 1);
  assert.deepEqual(errors, []);
  console.log("PASS 다시 열기 후 들여쓰기·문단·중첩 목록 보존");
} catch (error) {
  console.error("검증 실패:", error.message);
  throw error;
} finally {
  await browser?.close();
  // 소켓 종료 후 서버의 마지막 저장이 끝난 다음 테스트 자료만 지운다.
  await new Promise((resolve) => setTimeout(resolve, 35000));
  await db.delete(spaces).where(eq(spaces.id, spaceId));
  await db.delete(users).where(eq(users.id, userId));
  await sql.end();
}